-- FlashSale schema. Pomelo MySQL provider uses PascalCase column names by default;
-- see FlashSaleDbContext for explicit HasColumnName overrides when needed.
CREATE TABLE IF NOT EXISTS ticket (
  id          BIGINT NOT NULL AUTO_INCREMENT,
  Name        VARCHAR(50) NOT NULL,
  Description TEXT,
  StartTime   DATETIME NOT NULL,
  EndTime     DATETIME NOT NULL,
  Status      INT DEFAULT 0,
  UpdatedAt   DATETIME DEFAULT CURRENT_TIMESTAMP,
  CreatedAt   DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ticket_item (
  Id              BIGINT NOT NULL AUTO_INCREMENT,
  Name            VARCHAR(50) NOT NULL,
  Description     TEXT,
  StockInitial    INT DEFAULT 0,
  StockAvailable  INT DEFAULT 0,
  IsStockPrepared TINYINT(1) DEFAULT 0,
  PriceOriginal   BIGINT DEFAULT 0,
  PriceFlash      BIGINT DEFAULT 0,
  SaleStartTime   DATETIME,
  SaleEndTime     DATETIME,
  Status          INT DEFAULT 0,
  ActivityId      BIGINT NOT NULL,
  UpdatedAt       DATETIME DEFAULT CURRENT_TIMESTAMP,
  CreatedAt       DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (Id),
  KEY idx_ticket_item_activity (ActivityId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Parent ticket_order table (TASK-012). See note below for the monthly shards.
CREATE TABLE IF NOT EXISTS ticket_order (
  Id              BIGINT NOT NULL AUTO_INCREMENT,
  user_id         BIGINT NOT NULL,
  ticket_id       BIGINT NOT NULL,
  quantity        INT NOT NULL DEFAULT 0,
  order_status    INT NOT NULL DEFAULT 0,
  order_number    VARCHAR(64) NOT NULL,
  total_amount    BIGINT NOT NULL DEFAULT 0,
  terminal_id     VARCHAR(64),
  order_date      DATETIME NOT NULL,
  order_notes     VARCHAR(255),
  updated_at      DATETIME DEFAULT CURRENT_TIMESTAMP,
  created_at      DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (Id),
  UNIQUE KEY uk_ticket_order_number (order_number),
  KEY idx_ticket_order_user (user_id),
  KEY idx_ticket_order_ticket (ticket_id),
  KEY idx_ticket_order_id (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- NOTE: The migration target uses MONTHLY SHARDS like ticket_order_202407.
-- Mirrors Java TicketOrderAppServiceImpl where yearMonth is computed at runtime.
-- DDL for each new shard is generated by app code (or by an external cron) — not
-- checked in here because shards are append-only and TableCreateAutoService handles them.
-- If you want to ship pre-seeded shards for testing, add examples like:
--   CREATE TABLE IF NOT EXISTS ticket_order_202407 (...same shape as ticket_order above...) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 6. order_queue — async order tracking (TASK-015).
-- Mirrors Java order_queue (lines 135-147 of ticket_init.sql) with PascalCase columns
-- to match EF Core / Pomelo MySQL mapping convention used by ticket / ticket_item.
CREATE TABLE IF NOT EXISTS order_queue (
  Id           BIGINT NOT NULL AUTO_INCREMENT,
  Token        VARCHAR(64) NOT NULL,
  TicketId     INT NOT NULL,
  Quantity     INT NOT NULL,
  UserId       INT NOT NULL,
  Status       TINYINT NOT NULL DEFAULT 0 COMMENT '0=PENDING, 1=SUCCESS, 2=FAILED',
  OrderNumber  VARCHAR(64) NULL,
  Message      VARCHAR(255) NULL,
  CreatedAt    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (Id),
  UNIQUE KEY uk_order_queue_token (Token)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 7. outbox_event — transactional outbox for Kafka publish (TASK-015).
CREATE TABLE IF NOT EXISTS outbox_event (
  Id           BIGINT NOT NULL AUTO_INCREMENT,
  AggregateId  VARCHAR(64) NOT NULL COMMENT 'Token của order — dùng cho idempotency check phía consumer',
  EventType    VARCHAR(64) NOT NULL COMMENT 'ORDER_PLACED | …',
  Payload      TEXT NOT NULL COMMENT 'JSON của PlaceOrderMQMessage',
  Status       TINYINT NOT NULL DEFAULT 0 COMMENT '0=PENDING, 1=PUBLISHED',
  CreatedAt    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PublishedAt  DATETIME NULL,
  PRIMARY KEY (Id),
  KEY idx_status_created (Status, CreatedAt)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 8. idempotency_key — consumer gate chống Kafka retry duplicate (TASK-016).
-- Mirrors Java idempotency_key (lines 162-167 of ticket_init.sql) with
-- PascalCase columns to match EF Core / Pomelo MySQL convention.
CREATE TABLE IF NOT EXISTS idempotency_key (
  Token      VARCHAR(64) NOT NULL COMMENT 'Unique token từ PlaceOrderMqMessage',
  CreatedAt  DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ExpiresAt  DATETIME    NOT NULL COMMENT 'TTL — dùng cho cleanup job',
  PRIMARY KEY (Token),
  KEY idx_idempotency_expires (ExpiresAt)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
