-- FlashSale schema. Pomelo MySQL provider uses PascalCase column names by default;
-- see FlashSaleDbContext for explicit HasColumnName overrides when needed.
CREATE TABLE IF NOT EXISTS ticket (
  id          BIGINT NOT NULL AUTO_INCREMENT,
  Name        VARCHAR(50) NOT NULL,
  Description TEXT,
  StartTime   DATETIME NOT NULL,
  EndTime     DATETIME NOT NULL,
  Status      INT DEFAULT 0,
  UpdatedAt   DATETIME DEFAULT CURRENT_TIMESTAMP,
  CreatedAt   DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ticket_item (
  Id              BIGINT NOT NULL AUTO_INCREMENT,
  Name            VARCHAR(50) NOT NULL,
  Description     TEXT,
  StockInitial    INT DEFAULT 0,
  StockAvailable  INT DEFAULT 0,
  IsStockPrepared TINYINT(1) DEFAULT 0,
  PriceOriginal   BIGINT DEFAULT 0,
  PriceFlash      BIGINT DEFAULT 0,
  SaleStartTime   DATETIME,
  SaleEndTime     DATETIME,
  Status          INT DEFAULT 0,
  ActivityId      BIGINT NOT NULL,
  UpdatedAt       DATETIME DEFAULT CURRENT_TIMESTAMP,
  CreatedAt       DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (Id),
  KEY idx_ticket_item_activity (ActivityId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Parent ticket_order table (TASK-012). See note below for the monthly shards.
CREATE TABLE IF NOT EXISTS ticket_order (
  Id              BIGINT NOT NULL AUTO_INCREMENT,
  user_id         BIGINT NOT NULL,
  ticket_id       BIGINT NOT NULL,
  quantity        INT NOT NULL DEFAULT 0,
  order_status    INT NOT NULL DEFAULT 0,
  order_number    VARCHAR(64) NOT NULL,
  total_amount    BIGINT NOT NULL DEFAULT 0,
  terminal_id     VARCHAR(64),
  order_date      DATETIME NOT NULL,
  order_notes     VARCHAR(255),
  updated_at      DATETIME DEFAULT CURRENT_TIMESTAMP,
  created_at      DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (Id),
  UNIQUE KEY uk_ticket_order_number (order_number),
  KEY idx_ticket_order_user (user_id),
  KEY idx_ticket_order_ticket (ticket_id),
  KEY idx_ticket_order_id (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- NOTE: The migration target uses MONTHLY SHARDS like ticket_order_202407.
-- Mirrors Java TicketOrderAppServiceImpl where yearMonth is computed at runtime.
-- DDL for each new shard is generated by app code (or by an external cron) — not
-- checked in here because shards are append-only and TableCreateAutoService handles them.
-- If you want to ship pre-seeded shards for testing, add examples like:
--   CREATE TABLE IF NOT EXISTS ticket_order_202407 (...same shape as ticket_order above...) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
